Home page
PrangonGhose/Earthbnb-frontend pull request #2
Opened 2023-05-07 03:08 UTC by ShinhyoBelok

# Changes 🛠️ 

* Add Home page
* Add Home page CSS
* Add houses display 3 by 3
* Add houses fetch function
* Add dynamic arrow functionalities

2023-05-07 07:05 UTC, PrangonGhose commented on src/main.jsx
> +import './css/index.css';
I believe there is no `./css/index.css` file.

2023-05-07 07:06 UTC, PrangonGhose requested changes
Hi @ShinhyoBelok  :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 18:14 UTC, Gdiazdiaz approved these changes
Hey @ShinhyoBelok nothing to add at the moment, time to merge!

[Optional] I wanna ask if we can avoid using the universal tags (like h1, h2,) to style elements when pair-programming as it can cause issues.

<img src="https://media3.giphy.com/media/JJptubufblBJP3E3DK/giphy-downsized-medium.gif"/>

2023-05-08 19:09 UTC, merged

2023-05-09 18:30 UTC, Gdiazdiaz reviewed
Currently no changes need to be made, you can merge!

<img src="https://media1.giphy.com/media/xT1XGT9ersCCKjhVny/giphy.gif"/>